# Generated by Django 2.0.6 on 2018-06-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('descriptinon', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('descriptinon', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_yearly', models.FloatField()),
                ('employer_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('last_loan_taken', models.DateField()),
                ('last_loan_paid', models.DateField()),
                ('profile_updated', models.DateField()),
                ('client_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.ClientClass')),
                ('emplyment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.EmploymentType')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.Profile'),
        ),
    ]
