# Generated by Django 2.0.6 on 2018-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emplyment_type',
            new_name='employment_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_loan_paid',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_loan_taken',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
