# Generated by Django 2.0.6 on 2018-06-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_loan_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_loan_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
