# Generated by Django 2.0.6 on 2018-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_auto_20180624_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttype',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
