# Generated by Django 2.0.6 on 2018-07-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_telegramm'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramm',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
